# Generated by Django 5.2.6 on 2026-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobpost_max_wage_remove_jobpost_min_wage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('CL', 'Closed'), ('PA', 'Paused')], default='AC', max_length=2),
        ),
    ]
