# Generated by Django 5.2.6 on 2026-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobpost_owner_jobpost_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
