# Generated by Django 5.2.6 on 2025-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='max_wage',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='min_wage',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
