# Generated by Django 5.2.6 on 2026-05-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
